import os

print('Creating Directories:')
PATH = os.path.dirname(__file__)
GAF = os.path.join(PATH , 'GramianAngularFields')
TRAIN_PATH = os.path.join(GAF , 'TRAIN')
TRAIN_LONG = os.path.join(TRAIN_PATH , 'LONG')
TRAIN_SHORT = os.path.join(TRAIN_PATH , 'SHORT')
os.makedirs(TRAIN_LONG)
os.makedirs(TRAIN_SHORT)
TEST_PATH = os.path.join(GAF , 'TEST')
TEST_LONG = os.path.join(TEST_PATH , 'LONG')
TEST_SHORT = os.path.join(TEST_PATH , 'SHORT')
os.makedirs(TEST_LONG)
os.makedirs(TEST_SHORT)
DATA_PATH = os.path.join(PATH, 'TimeSeries')
os.mkdir(DATA_PATH)
MODELS_PATH = os.path.join(PATH, 'Models')
os.mkdir(MODELS_PATH)
print(GAF)
print(TRAIN_PATH)
print(TRAIN_LONG)
print(TRAIN_SHORT)
print(TEST_PATH)
print(TEST_LONG)
print(TEST_SHORT)
print(DATA_PATH)
print(MODELS_PATH)